### ISSUE TITLE
Controller meshes are missing from demo :(

### ISSUE THREAD

**Issue by DEF7** [GodotVR/godot_oculus#10]
Hi Bastiaan, thanks for your work getting VR into Godot. Just wanted to let you know that the project in the demo folder of this repo is missing the left/right controller obj files, and says as much when loading the project up. IIRC they are in one of your other repos. Thanks again.

**Comment by BastiaanOlij** [comment]
Thanks for the heads up, I'll get that fixed over the weekend :)

**Comment by DEF7** [comment]
Np. I just copied the OBJ files you have in your Oculus asset repo and that
solved the issue, but when I sent someone here to check out your Oculus
demo he was at a bit of a loss.

**Comment by BastiaanOlij** [comment]
I hope some day a few enhancements get put through on the asset library that allow me to just maintain one repository. In due time :)

**Comment by BastiaanOlij** [comment]
Ok, merged the restructure of the demo folder, should include all support files now in the same structure as the asset.
