### ISSUE TITLE
Button 6 (B button touched) isn't correctly set on right controller due to typo

### ISSUE THREAD

**Issue by UselessGhost** [GodotVR/godot_oculus#18]
https://github.com/GodotVR/godot_oculus/blob/master/src/ARVRInterface.cpp#L524

`ovrTouch_Y` should be `ovrTouch_B` to correctly register B button touches. Looks like it was an oversight when copying code for the right touch controller.

This seems to be affecting the godot-oculus asset on the Godot AssetLib.

**Comment by BastiaanOlij** [comment]
Sorry for the late response, I had totally missed this issue. Should be fixed now in the master (Godot 3.1 only)

**Comment by rodolforg** [comment]
Should this issue be closed?

**Comment by BastiaanOlij** [comment]
I think so :)
