### ISSUE TITLE
Need more informations to build from source.

### ISSUE THREAD

**Issue by sp82** [GodotVR/godot_oculus#6]
Hi,
I can compiled godot from source but I got the error while build the godot_oculus plugin: 

cl /Fosrc\ARVRInterface.obj /c src\ARVRInterface.cpp /TP /nologo -O2 -EHsc -DNDEBUG /MT /IC:\src\OculusSDK\LibOVR\Include /I. /Igodot_headers /Iglad
ARVRInterface.cpp
godot_headers\gdnative/string.h(39): fatal error C1083: Non è possibile aprire il file inclusione: 'wchar.h': No such file or directory

I have no idea why, please help me build it, would be great have more instructions how to setup the build enviroment in the readme.
I also suggest to add your youtube videos how to user openvr because without that I would never get it works.
Best Regards,
Salvatore.

**Comment by BastiaanOlij** [comment]
That is strange... wchar.h is a standard C library for unicode handling and should be part of your compiler installation. Which compiler are you using?

**Comment by sp82** [comment]
I have installed Visual Studio Community 2017+BuildTools2017 and QTCreator+mingw53_32.
If you give me some suggestion I will uninstall everything and install only the right solution.
Maybe installing only the BuildTools201X and I'll be fine.

**Comment by BastiaanOlij** [comment]
Sounds like what I have installed (VS 2017). You might not have the Windows SDK downloaded, 2017 is a lot more conservative in what it downloads.. though it compiled Godot so that should suggest you have enough...

**Comment by sp82** [comment]
I installed the c++/.net support and now I can compile it!
Best Regards,
Salvatore.
